netobserv/netobserv-ebpf-agent

deployments/flp-daemonset-cap.yml
deployments/flp-daemonset.yml
deployments/flp-service.yml

Example deployments had some missing entries, and other configuration properties were updated.

Fixed example deployments

---

pkg/grpc/grpc_test.go
pkg/grpc/server.go

We need to instrument HTTP calls in flowlogs-pipeline. This PR allows injecting interceptors in the GRPC Server.

NETOBSERV-333: allow overriding default GRPC server options

---

e2e/cluster/base/03-flp.yml
e2e/kafka/kafka_test.go
e2e/kafka/manifests/11-kafka-cluster.yml
e2e/kafka/manifests/20-flp-transformer.yml

Some breaking changes were added to FLP, making the e2e tests to fail. This PR fixes it.

Fix FLP in e2e tests

---

e2e/basic/common.go
e2e/basic/flow_test.go
e2e/basic/manifests/pods.yml
e2e/cluster/tester/loki.go

Tests the following issue: https://github.com/netobserv/netobserv-ebpf-agent/pull/39#issuecomment-1173831297

Added ICMP single-packet test

---

e2e/basic/flow_test.go

In order to ensure that the tests will fail if ICMP packets aren't accounted correctly, it increases the number of tested packets.

Increased number of ICMP test packets

---

pkg/flow/deduper.go
pkg/flow/deduper_test.go

This reverts commit 7c2b292954f491dea9ed579976ff3828ccfa4b7d.

Revert "NETOBSERV-755: ignore flow direction in deduplication (#74)"

---

docs/profiling.md

update agent spec for profiling docs

---

Makefile

@msherif1234 this is the same fix as in the operator. Also adding a 2>/dev/null on which to avoid unnecessary errors displayed repeatedly with podman

Fix makefile image-build with podman

---

e2e/cluster/kind.go

update kind image to more recent version to work with latest fedora env
n/a

update kind image to recent image

---

pkg/ebpf/tracer.go

need to reset global counters after we read them
n/a

NETOBSERV-1605: reset ebpf global counters after reading them

---

.tekton/netobserv-ebpf-agent-pull-request.yaml
.tekton/netobserv-ebpf-agent-push.yaml

Removed base image ref in konflux

---

pkg/ifaces/watcher.go

when run the following script in test namespace on specific nodes
```shell
while sleep 0.1 ;do oc run --image-pull-policy=Always --restart=Never -n test --rm -ti --overrides '{"spec":{"nodeName":"ip-10-0-1-148.ec2.internal"}}' --image quay.io/centos/centos:stream9 myclient -- id; done
```
it was noticed lost of netlink sock threads are keep getting created and never get deleted
```sh
lsof -p <netobserv_pid>
netobserv 16577 root   68u     sock    0,8      0t0     163185 protocol: NETLINK
netobserv 16577 root   69u     sock    0,8      0t0     164377 protocol: NETLINK
netobserv 16577 root   70u     sock    0,8      0t0     163189 protocol: NETLINK
netobserv 16577 root   71u     sock    0,8      0t0     162297 protocol: NETLINK
```
from the corefile analysis
The Fix is to watch for netns …

NETOBSERV-1805: threads are leaking with continous adding and deletinng pods

---

.tekton/netobserv-ebpf-agent-pull-request.yaml
.tekton/netobserv-ebpf-agent-push.yaml

Add prefetch configuraton for konflux
n/a

NETOBSERV-1633: Add prefetch configuration for konflux

---

.github/workflows/push_image.yml
.github/workflows/push_image_pr.yml
.github/workflows/release.yml
Dockerfile
Makefile
cmd/netobserv-ebpf-agent.go

- Reducing the Dockerfile dependencies allows faster dev builds
- Align also with other repos wrt build date / version (it was ignored in code until now)

Align build steps - distinguish clean vs dev builds

---

.tekton/netobserv-ebpf-agent-1-7-push.yaml

Fix konflux nudges for 1.7

---

.tekton/pipeline-ref.yaml

Added new rpms check task in konflux
n/a

Added new rpms check task in konflux

---

.tekton/pipeline-ref.yaml

Fixing source build image tagging in konflux
n/a

Fixing source build image tagging in konflux

---

pkg/tracer/tracer.go

PCA maps need to be unpinned 
n/a

make sure to remove pca map pinning

---

pkg/pbflow/proto.go

As per @memodi 's request: https://issues.redhat.com/browse/NETOBSERV-1935?focusedId=26318693&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-26318693

Change netevents debug logs to trace

---

.tekton/pipeline-ref.yaml

Removing konflux deprecated results

---

pkg/ifaces/watcher.go

Signed-off-by: Mohamed Mahmoud <mmahmoud@redhat.com>
(cherry picked from commit 6feda504f2134ab132704db5e89aecb8fd522e54)
n/a

NETOBSERV-2077: switch to syncMap to handle concurrency issues [BP 1.8]

---

.github/workflows/pull_request_e2e.yml

https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
n/a

update actions/upload-artifact to v4

---

Dockerfile.downstream

@OlivierCazade I need also your recent commits on `main` in order to apply this patch

FIPS compliance

---

Dockerfile.downstream

Bump downstream dockerfile to 1.9.0

bump-1.9.0

---

deployments/flp-daemonset-cap.yml
deployments/flp-daemonset.yml
deployments/flp-service.yml

Fix outdated examples

---

.tekton/netobserv-ebpf-agent-ystream-pull-request.yaml

Fixing typo in konflux image target
n/a

Fixing typo in konflux image target

---

pkg/metrics/metrics.go

Add missing ipsec prom counter to flowenrich definition

---

pkg/flow/limiter_test.go

Actually, re-reading my code from this morning, it was unnecessarily complex :-)

Simplify previous test fix

---

.ci-operator.yaml

update to golang 1.24 in CI
