netobserv/netobserv-ebpf-agent

- cmd/netobserv-agent.go
- deployments/README.md
- deployments/flp-daemonset.yml
- deployments/flp-service.yml
- examples/performance/deployment.yml
This will facilitate setting the Node IP in the descriptor when the
flowlogs-pipeline is deployed as daemonset.
it also includes two deployment descriptors for manual testing
> Separate HOST from PORT in the env configuration

- .github/workflows/pull_request.yml
"make fmt" silently formats the code so you won't get CI errors derived from a wrong text formatting.
Removing this target invocation makes the PR fail if the code is not well formatted (goimports plugin from make lint)
> Remove fmt from PR make target

- README.md
- deployments/README.md
- deployments/flp-daemonset-cap.yml
- deployments/flp-daemonset.yml
- deployments/flp-service.yml
- pkg/agent/agent.go
- pkg/agent/agent_darwin.go
- pkg/agent/agent_linux.go
- pkg/ebpf/tracer.go
* Explain how to configure/run in Vanilla K8s.
* Explain how/when to run with capabilities instead of full privileges.
* It also moves the memlock removal to the agent initialization, as it needs to run only once.
> NETOBSERV-307 & NETOBSERV-308: changed example deployments + documentation

- cmd/netobserv-ebpf-agent.go
- docs/config.md
- pkg/agent/config.go
Optionally opens a port for remote profiling using `go pprof` tool: https://go.dev/blog/pprof
> Enable remote profiling

- cmd/netobserv-ebpf-agent.go
- docs/config.md
- pkg/agent/agent.go
- pkg/agent/config.go
- pkg/flow/deduper.go
- pkg/flow/deduper_test.go
Detects when the same flow is detected in different interfaces and then forwards the flow from the first interface it was received from.
In hosts with low traffic it decreased the number of flows by 20% and hosts with higher traffic, by 40%.
However, it seems that in OpenShift we still could have some duplicates as the same flow can be detected from two agents in different hosts. In that case, a second deduplication should be performed at flowlogs-pipeline level.
> NETOBSERV-578: deduplicate flows at agent level

- go.mod
- go.sum
- pkg/agent/agent.go
- pkg/ebpf/tracer.go
- pkg/flow/account.go
- vendor/github.com/netobserv/gopipes/pkg/node/node.go
- vendor/github.com/netobserv/gopipes/pkg/node/options.go
- vendor/modules.txt
* Removed a pipeline stage that became unneeded after refactoring the tracer to share the channel for all the interfaces.
* Log is not flooded anymore when hundreds of flows were received via ringbuffer
* Updated to go-pipes 0.2.0 and allow setting the buffer length of the pipeline stages
* Minor log messages improvements
> Some code improvements

- .github/workflows/pull_request.yml
- .github/workflows/pull_request_e2e.yml
- .github/workflows/push_image.yml
- .github/workflows/push_image_pr.yml
- .github/workflows/release.yml
- .golangci.yml
- Dockerfile
- examples/performance/Dockerfile_packet_counter
- scripts/generators.Dockerfile
Backport of https://github.com/netobserv/netobserv-ebpf-agent/pull/71
> NETOBSERV-743: update build image & CI tests to Go 1.18 (4.12 backport)

- pkg/flow/deduper.go
- pkg/flow/deduper_test.go
Being also backported to 4.12: https://github.com/netobserv/netobserv-ebpf-agent/pull/75
This is technically a breaking change, as some flows that were marked as "Duplicate: false" will be now marked as "Duplicate: true".
From the Netobserv user experience, this shouldn't have any visible impact as long as they don't set the `agent.debug.env.DEDUPER_JUST_MARK=false` flag.
It should have the positive impact of more accurate metric aggregations.
> NETOBSERV-755: ignore flow direction in deduplication

- .github/workflows/pull_request.yml
- .github/workflows/pull_request_e2e.yml
PR github actions works well in `release-4.12` branch, but doing a PR againts `main` tries still to get input from GH actions that were removed and don't exist anymore:
Comparing `.github` folder between `main` and `release-4.12` this seems to be the unique difference. So I unified both files.
> Fix github actions

- .github/workflows/pull_request.yml
- .github/workflows/pull_request_e2e.yml
The goal is to allow branch protection rule with these status checks, but we don't want to have to modify every time we update the go version (as they're referred to with their go version included when startegy matrix is used)
> ghactions: remove strategy matrix

- docs/config.md
- pkg/agent/agent.go
- pkg/agent/config.go
- pkg/exporter/grpc_proto.go
- pkg/exporter/grpc_proto_test.go
- pkg/exporter/proto.go
- pkg/test/channels.go
Only for GRPC exporter, payloads with more than 10000 flows (default configurable value) are split in multiple messages that are submitted sequentially.
> NETOBSERV-617: split big payloads in GRPC exporter

- Dockerfile
- docs/architecture.md
- pkg/ebpf/tracer.go
- pkg/flow/tracer_map.go
The flush operation was done asynchronously in another goroutine so it was frequent that, when the agent is shutdown, the destination channel was closed in the main goroutine while the flush goroutine was performing the channel submission.
This PR verifies, before channel send, that the context of the main goroutine is not closed.
This PR also removes some warnings on shutdown due to the agent trying to close unexisting resources of FLP and the Console Plugin, when they are removed just before the agent shutdown.
> NETOBSERV-661: fix crash on shutdown

- pkg/agent/agent.go
- pkg/agent/ip.go
- pkg/exporter/grpc_proto.go
- pkg/exporter/grpc_proto_test.go
- pkg/exporter/ipfix.go
- pkg/grpc/client.go
- pkg/grpc/grpc_test.go
- pkg/utils/utils.go
This PR fixed two issues
1- when hostIP is IPv6 address we endup with following error when gRPC try to connect
```bash
collector="2604:1380:4642:7e00::5b:2055" component=exporter/GRPCProto error="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp: address 2604:1380:4642:7e00::5b:2055: too many colons in address\""
```
for IPv6 we need to use `[2604:1380:4642:7e00::5b]:2055` format.
2- on single stack ipv6 cluster with IPType=="any" , ipv4 DNS address was incorrectly used which prevented ebpf agent to come up and the pod stay in crashloop with this error:-
```bash
time="2023-02-16T21:06:17Z" level=fatal msg="can't instantiate NetObserv eBPF Agent" error="acquiring Agent IP: can't establish an external connection dial udp 8.8.8.8:80: …
```
> NETOBSERV-889: fix too many colons in address error

- pkg/exporter/ipfix.go
This PR fixes https://github.com/netobserv/netobserv-ebpf-agent/issues/93
> Fix v6 ipfix export

- pkg/exporter/kafka_proto.go
- pkg/exporter/kafka_proto_test.go
Add keys to each kafka message. Kafka then ensure that all messages with the same key will be consumed by the same client.
We use src and destination IP as key so all messages from a connection will be consumed by the same transformer so connection tracking metrics will be accurate.
> NETOBSERV-926: Added key to kafka message for connection tracking consistency

- pkg/agent/ip.go
We need to filter out interfaces with linklocal ips when we decide which socket type to use to connect to google dns server here is an example 
```shell
2: enp0s20f0u5u2c2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN group default qlen 1000
link/ether fa:14:54:36:5a:55 brd ff:ff:ff:ff:ff:ff
inet 169.254.3.1/24 brd 169.254.3.255 scope link dynamic noprefixroute enp0s20f0u5u2c2
valid_lft 855315sec preferred_lft 855315sec
inet6 fe80::2021:58f:8cf9:eca6/64 scope link noprefixroute 
valid_lft forever preferred_lft forever
```
> NETOBSERV-977: some interfaces on single stack cluster can have both ipv4 and ipv6 linklocal

- pkg/agent/ip.go
We need to filter out those interfaces when we decide which socket type to use to connect to google dns server
Signed-off-by: msherif1234 <mmahmoud@redhat.com>
(cherry picked from commit 9a3f45e9bf299914462aacb49abc88682f168030)
> NETOBSERV-977: some interfaces could have both ipv4 and ipv6 linklocal [backport]

- .github/workflows/push_image.yml
- .github/workflows/push_image_pr.yml
- .github/workflows/release.yml
- .mk/shortcuts.mk
- Dockerfile
- Makefile
- README.md
Implements multi arch builds and add documentation and consistency
```
$ make help
Usage:
make <target>
General
help                  Display this help.
vendors               Check go vendors
prereqs               Check if prerequisites are met, and install missing dependencies
Develop
fmt                   Run go fmt against code.
lint                  Lint the code
generate              Generate artifacts of the code repo (pkg/ebpf and pkg/proto packages)
docker-generate       Create the container that generates the eBPF binaries
compile               Compile ebpf agent project
test                  Test code using go test
coverage-report       Generate coverage report
coverage-report-html  Generate HTML coverage report
tests-e2e             Run e2e tests
Images
image-build …
```
> NETOBSERV-848 eBPF agent multi-arch builds (upstream)

- Dockerfile
Tested locally with both podman and docker.
> Fix dockerfile targetarch scope with docker

- pkg/utils/utils.go
ppc64le and s390x for some reason they use `uint8` instead of `int8` for this type
https://pkg.go.dev/syscall#Utsname
leading to this build error
```sh
6.662 pkg/utils/utils.go:80:54: cannot use buf.Release[:] (value of type []uint8) as []int8 value in argument to utsnameStr
```
Fix to create two instances of utils package based on arch check
- unit-tests
```sh
docker images
REPOSITORY                               TAG            IMAGE ID       CREATED          SIZE
quay.io/mmahmoud/netobserv-ebpf-agent    main-s390x     bd818f928693   24 seconds ago   117MB
quay.io/mmahmoud/netobserv-ebpf-agent    main-amd64     1b01b143841e   5 minutes ago    118MB
quay.io/netobserv/netobserv-ebpf-agent   main-amd64     1b01b143841e   5 minutes ago    118MB
quay.io/mmahmoud/netobserv-ebpf-agent …
```
> fix build for s390x and ppc64le

- pkg/ebpf/tracer.go
shrink dnsmap to 1 entry when the feature is not enabled to optimize memory usage
Note: I have to move code out of FlowFetcher function because lint hit complexity limit in that function
> Shrink DNSMap if DNS not enabled to save memory

- pkg/ebpf/tracer.go
there is some behavior difference with maps between rhel8 and rhel9
on rhel8 it seems maps not even allocated until its populated leading to this issue while in rhel9 that doesn't seem to be the case.
To be on safe side lets make sure maps pointer is != nil before doing invoking `Iterate`
> NETOBSERV-1223: check Maps to make sure not nil b4 iterating

- go.mod
- go.sum
- pkg/ebpf/tracer.go
- pkg/ifaces/informer.go
- pkg/ifaces/poller_test.go
- pkg/ifaces/registerer_test.go
- pkg/ifaces/watcher.go
- pkg/ifaces/watcher_test.go
- vendor/github.com/fsnotify/fsnotify/.editorconfig
- vendor/github.com/fsnotify/fsnotify/.gitattributes
- vendor/github.com/fsnotify/fsnotify/.gitignore
- vendor/github.com/fsnotify/fsnotify/.mailmap
- vendor/github.com/fsnotify/fsnotify/AUTHORS
- vendor/github.com/fsnotify/fsnotify/CHANGELOG.md
- vendor/github.com/fsnotify/fsnotify/CONTRIBUTING.md
- vendor/github.com/fsnotify/fsnotify/LICENSE
- vendor/github.com/fsnotify/fsnotify/README.md
- vendor/github.com/fsnotify/fsnotify/fen.go
- vendor/github.com/fsnotify/fsnotify/fsnotify.go
- vendor/github.com/fsnotify/fsnotify/inotify.go
- vendor/github.com/fsnotify/fsnotify/inotify_poller.go
- vendor/github.com/fsnotify/fsnotify/kqueue.go
- vendor/github.com/fsnotify/fsnotify/open_mode_bsd.go
- vendor/github.com/fsnotify/fsnotify/open_mode_darwin.go
- vendor/github.com/fsnotify/fsnotify/windows.go
- vendor/modules.txt
today netobserv agent only subscribe to watch interface in default netns
for PODs with VF SRIOV interfaces they only show in custom netns made them invisible to network observability to fix this netobserv agent interface manager component needs to netns aware 
needs https://github.com/netobserv/network-observability-operator/pull/406 to setup netns mount
> NETOBSERV-1283: Make ifaces watcher netns aware

- pkg/flow/deduper.go
- pkg/flow/deduper_test.go
backport fix for #174
Signed-off-by: msherif1234 <mmahmoud@redhat.com>
(cherry picked from commit cca4aa32f9c3b40d00a1c1225f25ed1ffeea628c)
> NETOBSERV-1240: prefer flows with DNS records when checking for DNS [backport]

- pkg/ifaces/watcher.go
replace netns errors with warning since the default case is running 
with `privileged: false` 
> NETOBSERV-1317: change netns errors to warnings to avoid confustion

- pkg/agent/agent.go
- pkg/agent/config.go
- pkg/flow/tracer_map.go
- pkg/flow/tracer_ringbuf.go
doing GC for ring buff was adding GC cpu overhead while its not really needed, this was very obvious when use `sampling: 1` and run with load `./hey-ho.sh -r 5 -z 10m -p -n 3 -q 800 -d 10`
n/a
> NETOBSERV-1312: remove GC from ring buff mapper not needed

- pkg/ifaces/watcher.go
…#186)
Signed-off-by: msherif1234 <mmahmoud@redhat.com>
(cherry picked from commit c8c9e6af13ba806aa6fef6f649ea0f126c541cb7)
n/a
> NETOBSERV-1317: change netns errors to warnings to avoid confustion [1.4 backport]

- pkg/agent/agent.go
- pkg/agent/config.go
- pkg/flow/tracer_map.go
- pkg/flow/tracer_ringbuf.go
Signed-off-by: msherif1234 <mmahmoud@redhat.com>
(cherry picked from commit 46af41c78944df06f3967ea98eeaaeaca2bc69a0)
n/a
> NETOBSERV-1312: remove GC from ring buff mapper not needed [1.4 backport]

- pkg/ebpf/tracer.go
we can have stale map when the agent pod has been terminated
n/a
* [] Will this change affect NetObserv / Network Observability operator? If not, you can ignore the rest of this checklist.
> close all maps when agent is terminating

- pkg/agent/agent.go
Fix kafka writer configuration causing kafka to ignore key for partition distribution
n/a
> NETOBSERV-926: Fix kafka and connection tracking

- docs/config.md
- go.mod
- go.sum
- pkg/agent/agent.go
- pkg/agent/config.go
- pkg/agent/filter.go
- pkg/agent/filter_test.go
- pkg/agent/packets_agent.go
- vendor/modules.txt
We have a use case where it's easy for us to pass the IP(s) of the interfaces we'd like to monitor as an environment variable but quite a bit harder to know the names of those interfaces in advance.
Here's a first pass at adding another filter type that allows/disallows interfaces based on whether it's associated with the passed in IPs. There's still some logic around the poller/watcher for interfaces that'd need some additions to also watch for when IPs are attached/unattached and I'm sure other things that would need updates too.
Is there any interest in adding a feature like this? Happy to change approach from what I have here or otherwise do what still needs done to get it merged if so!
> Filter interfaces by their associated IPs

- pkg/agent/agent.go
Backporting https://github.com/netobserv/netobserv-ebpf-agent/pull/195
> NETOBSERV-926: Fix kafka writer configuration ... [1.4 backport]

- .github/workflows/pull_request.yml
- .github/workflows/pull_request_e2e.yml
- .github/workflows/push_image.yml
- .github/workflows/push_image_pr.yml
- .github/workflows/release.yml
- Makefile
- go.mod
- go.sum
- scripts/generators.Dockerfile
- vendor/modules.txt
update Github actions to use go1.21
make sure to set GOTOOLCHAIN to `local` to avoid updating `go.mod`
by setting this envvar
`go env -w GOTOOLCHAIN="local"`
n/a
> update github actions to use go1.21

- .golangci.yml
- Dockerfile
- examples/performance/Dockerfile_packet_counter
> NETOBSERV-1451: Bump ubi 9.3 / go 1.21

- pkg/decode/decode_protobuf.go
- pkg/decode/decode_protobuf_test.go
- pkg/exporter/proto.go
- pkg/flow/deduper.go
- pkg/flow/deduper_test.go
- pkg/utils/utils.go
need to drive interface name from idx before populating the duplist
config used to test
```yaml
debug:
env:
DEDUPER_JUST_MARK: "false"
DEDUPER_MERGE: "true"
```
https://github.com/netobserv/flowlogs-pipeline/pull/546
> NETOBSERV-1298: Interface name wasn't populated yet so add func to find ifname

- deployments/README.md
- deployments/flp-daemonset-cap.yml
- deployments/flp-daemonset.yml
- deployments/flp-service.yml
- deployments/perms.yml
The stand-alone ebpf and flp were implemented against an older version of flp.
This PR updateds the README and yml files to work with the current flp.
n/a
> updated README and yml files

- pkg/utils/utils.go
need to be consistent when can't find interface name and always use `unknown` string
n/a
> use unknown for interface we can't detect instead of ""

- pkg/agent/agent.go
- pkg/flow/deduper.go
- pkg/flow/deduper_test.go
- pkg/utils/utils.go
use cached APIs and avoid excessive syscalls which showed high cpu utilization
```yaml
advanced:
env:
DEDUPER_JUST_MARK: "false"
DEDUPER_MERGE: "true" 
```
n/a
> use cached api to retrieve interface name to avoid highcpu

- go.mod
- pkg/agent/agent.go
- pkg/agent/config.go
- pkg/agent/packets_agent.go
- pkg/ebpf/tracer.go
- pkg/exporter/grpc_proto.go
- pkg/exporter/grpc_proto_test.go
- pkg/exporter/kafka_proto.go
- pkg/exporter/kafka_proto_test.go
- pkg/flow/account.go
- pkg/flow/account_test.go
- pkg/flow/tracer_map.go
- pkg/flow/tracer_ringbuf.go
- pkg/metrics/metrics.go
- pkg/metrics/metrics_test.go
- pkg/prometheus/prom_server.go
- pkg/prometheus/prom_server_test.go
- pkg/test/tracer_fake.go
add promo metrics to eBPF agent with the ability to export metrics to promo Server
tested locally using standalone ebpf-agent
- `sudo LOG_LEVEL=debug FLOWS_TARGET_HOST=127.0.0.1 FLOWS_TARGET_PORT=9999   METRICS_PROMO_ENABLE="true" ./bin/netobserv-ebpf-agent`
- from another terminal `curl 127.0.0.1:9090/metrics | grep ebpf_agent`
results
```sh
:-- # TYPE ebpf_agent_err_can_not_delete_flow_entries counter
-ebpf_agent_err_can_not_delete_flow_entries{operational="errors while deleting flows"} 0
-:# HELP ebpf_agent_err_can_not_write_to_grpc Error can not write to GRPC
--# TYPE ebpf_agent_err_can_not_write_to_grpc counter
:-ebpf_agent_err_can_not_write_to_grpc{operational="err_export_by_grpc"} 0
- # HELP ebpf_agent_hashmap_evictions Number of hashmap evictions
8# TYPE …
```
> NETOBSERV-557: add eBPF agent metrics for troubleshooting

- pkg/agent/agent.go
- pkg/exporter/grpc_proto.go
- pkg/exporter/kafka_proto.go
- pkg/exporter/kafka_proto_test.go
- pkg/flow/tracer_map.go
- pkg/metrics/metrics.go
- All errors can now be found from metric "errors_total"
- Use error name and exporter as labels
> Share errors counter across components

- Makefile
- README.md
- scripts/agent.yml
- scripts/kind-cluster.sh
add Kind development env for netobserv agent
```sh
create-and-deploy-kind-cluster
destroy-kind-cluster
```
n/a
> Add KinD deployment env for developement

- pkg/agent/agent.go
- pkg/agent/agent_test.go
- pkg/agent/packets_agent.go
- pkg/ebpf/tracer.go
- pkg/exporter/grpc_proto.go
- pkg/exporter/grpc_proto_test.go
- pkg/exporter/kafka_proto.go
- pkg/exporter/kafka_proto_test.go
- pkg/flow/account.go
- pkg/flow/deduper.go
- pkg/flow/deduper_test.go
- pkg/flow/limiter.go
- pkg/flow/limiter_test.go
- pkg/flow/tracer_map.go
- pkg/flow/tracer_ringbuf.go
- pkg/metrics/metrics.go
- pkg/metrics/metrics_test.go
- pkg/test/tracer_fake.go
- Use just two shared metrics for eviction counters: on for eviction events and one for flows; shared across ringbuf/map implementations and labelled as such
- Report more errors via metrics
> NETOBSERV-1533: refine metrics for dashboard creation

- docs/config.md
- pkg/agent/config.go
> Add direct-flp mode documentation

- pkg/agent/config.go
> NETOBSERV-1474: change dup mode to use list as the default

- pkg/agent/agent.go
- pkg/agent/config.go
- pkg/metrics/metrics.go
- pkg/prometheus/prom_server.go
Add the ability to use TLS for the metrics server,
n/a
> NETOBSERV-1532: add TLS support to ebpf agent metrics config

- pkg/ebpf/tracer.go
fix ebpf program name for older kernel
n/a
> NETOBSERV-1473: fix ebpf program name for older kernel

- pkg/ebpf/tracer.go
add missing maps in case we are running old kernel
n/a
> NETOBSERV-1645: make sure to copy all maps for older kernels

- pkg/ebpf/tracer.go
- pkg/ifaces/informer.go
- pkg/ifaces/poller.go
- pkg/ifaces/poller_test.go
- pkg/ifaces/registerer_test.go
- pkg/ifaces/watcher.go
- pkg/ifaces/watcher_test.go
while netns is getting it was noticed the associated netnsHandle keep changing for sometime then become stable and at that point `netlinkSubscribeAt` will succeed
so added retry loop and avoid the early creation of netnshandle till things become more stable
n/a
> NETOBSERV-1697: Add retry around netlinkSubscribeAt

- pkg/agent/config.go
use default values for flow filter cidr and action
n/a
> flow filtering default settings for cidr and action

- pkg/ebpf/tracer.go
Today if ebpf agent pod is killed with `SIGKILL` the clean up code never get a chance to remove all TC filters and qdisc installed 
this PR check all previously installed TC filters and remove them
n/a
> NETOBSERV-1732: add logic to lkup all previous tc filters and remove them

- pkg/ebpf/tracer.go
when update FC the TCS handle is still attached to interface 
n/a
> NETOBSERV-1743: handle file exits error using TCx hooks and update FC

- pkg/ebpf/tracer.go
- pkg/kernel/kernel_utils.go
- pkg/kernel/kernel_utils_test.go
- pkg/utils/utils.go
move kernel version check to its own pkg
n/a
> NETOBSERV-1739 move kernel version check to its own pkg

- examples/packetcapture-dump/client/packetcapture-client.go
- pkg/agent/agent.go
- pkg/agent/config.go
- pkg/agent/packets_agent.go
- pkg/decode/decode_protobuf.go
- pkg/exporter/direct_flp.go
- pkg/exporter/grpc_packets.go
- pkg/utils/packets.go
This PR allows pcap parsing to generic map. Check [CLI implementation](https://github.com/netobserv/network-observability-cli/pull/61) for usage.
https://github.com/netobserv/network-observability-cli/pull/61
> NETOBSERV-1703 Add enrichment in packet capture

- pkg/agent/agent.go
- pkg/agent/packets_agent.go
- pkg/ebpf/tracer.go
- pkg/ifaces/watcher.go
- pkg/test/tracer_fake.go
Today ebpf agent only cleanup pods when the pod restarts but in this issue pods where continosly recreated but it was never deleted causing the fd leak
this issue only in v1.6.1 releases because of https://github.com/netobserv/netobserv-ebpf-agent/pull/358 fix partily and introduction of TCX hook
n/a
> NETOBSERV-1805: make sure to cleanup pod veth's hooks when pods is deleted

- pkg/ebpf/tracer.go
PCA feature was failing to load ebpf prog with this error
`loading and assigning BPF objects: field KfreeSkb: program kfree_skb: load program: permission denied: combined stack size of 2 calls is 544. Too large (1 line(s) omitted)"`
n/a
> NETOBSERV-1882 make sure pkt drop hook is disabled for PCA feature

- pkg/ifaces/watcher.go
Signed-off-by: Mohamed Mahmoud <mmahmoud@redhat.com>
(cherry picked from commit 6111b9846d226a1478490514430807be86ca6e44)
n/a
> NETOBSERV-1805: threads are leaking with continous adding and deleting pods [BP 1.7]

- .tekton/pipeline-ref.yaml
Fixing konflux results and adding rpms task
n/a
> Fixing konflux results and adding rpms task

- pkg/agent/packets_agent.go
> fix make sure flow filter is on by default for pca

- Makefile
- README.md
- e2e/README.md
- e2e/basic/common.go
- e2e/basic/flow_test.go
- e2e/cluster/base/02-loki.yml
- e2e/cluster/kind.go
- e2e/cluster/kind_test.go
- e2e/cluster/tester/loki.go
- e2e/cluster/tester/pods.go
- e2e/ipfix/ipfix_test.go
- e2e/kafka/kafka_test.go
- e2e/kafka/manifests/10-kafka-crd.yml
Improve / fix some issues with e2e tests:
- Add more logs; print some useful information such as when cluster is still up
- Improve readiness (e.g: had agents pods crashing)
- Use more up to date templates for loki and kafka (similar to what we have in docs repo)
- Add doc
n/a
> Improve e2e troubleshooting

- README.md
Related discussion: https://github.com/netobserv/network-observability-operator/discussions/843
> Add running doc info

- hack/build-bytecode-images-multi.sh
Add missing `,` after additional metrics map
n/a
> Add missing , after additional metrics name

- pkg/metrics/metrics.go
- pkg/tracer/tracer.go
New metric: `netobserv_agent_flows_enrichment_total`
The goal is to be able to track regressions in terms of quantity of flows being enriched.
Example of query:
`sum(rate(netobserv_agent_flows_enrichment_total[1m])) by (hasDNS, hasRTT, hasDrops, hasNetEvents)`
Or, to have the proportion of flows with RTT for instance:
`100 * sum(rate(netobserv_agent_flows_enrichment_total{hasRTT="true"}[1m])) / sum(rate(netobserv_agent_flows_enrichment_total[1m]))`
> Add enrichment stats

- pkg/tracer/tracer.go
additional map include interfaces list the packets go through regardless if agent features are
enabled or not
n/a
> Always set the additional map size

- pkg/pbflow/proto.go
Ref: https://github.com/netobserv/netobserv-ebpf-agent/pull/539
> NETOBSERV-2084: (nit) no need to copy map anymore [backport 1.8]

- pkg/ifaces/watcher.go
there is race condition when accessing nsDone map from multiple go routines this PR refactor the code and use syncMap instead of regular map
Fixes #524 
test cases:
- multiple agent pods restarts via fc config changes no sign of error/restarts
- test FD and netlink leaks
- ran script to create and delete 10 ns while agent is up
- bring up 10 netns 1st then bring up the agent
n/a
> NETOBSERV-2077: use syncMap to handle concurrency issues in intf watcher

- Dockerfile.downstream
This fix the multiarch build with konflux.
n/a
> Align downstream dockerfile with the upstream one

- Dockerfile.downstream
Fix arg usage for downstream builds
n/a
> release-1.8: Fix arg usage for downstream builds

- .mk/bc.mk
> test fix for bc workflow

- .mk/bc.mk
> fix pkt xlat program name in the bc image

- pkg/pbflow/flow.pb.go
- proto/flow.proto
This is just to clarify in code comments that it's now unused
> nit: unused Duplicate field in protobuf

- pkg/ifaces/informer.go
- pkg/ifaces/poller.go
- pkg/ifaces/poller_test.go
- pkg/ifaces/registerer_test.go
- pkg/ifaces/watcher.go
- pkg/ifaces/watcher_test.go
bpfman needs access to netns string not the nshandle
n/a
> bpfman needs to have ns string instead of the nshandle

- pkg/metrics/metrics.go
- pkg/tracer/tracer.go
> NETOBSERV-2215: Add missing IPSec per flow hasIPSec metrics

- .github/workflows/release.yml
- .gitignore
- Dockerfile
- Makefile
See also (same changes): https://github.com/netobserv/flowlogs-pipeline/pull/932
> Disable cgo on upstream builds and attach binaries to releases

- pkg/tracer/tracer.go
Otherwise we're getting this error while running pca:
```
time="2025-05-12T11:03:12Z" level=fatal msg="[PCA] can't instantiate NetObserv eBPF Agent" error="loading and assigning BPF objects: field IpsecEgressMap: map ipsec_egress_map: pin by name: missing MapOptions.PinPath"
```
> Fix pca - need to unpin ipsec maps

- README.md
- deployments/flp-daemonset-cap.yml
Hey @msherif1234 , FYI I picked up your descriptions from [there](https://github.com/netobserv/network-observability-operator/blob/main/controllers/ebpf/internal/permissions/permissions.go#L21-L24), but also, while testing I'm finding that SYS_RESOURCE isn't needed anymore. Not sure if that's a moving requirement related to a code change from us, or from the linux kernel, or something else ...
Anyway, I'll the change also in the operator and we'll verify that with tests on different ocp versions and enabled features.
See also: https://github.com/netobserv/network-observability-operator/pull/1484
> NETOBSERV-2101: document needed caps, remove CAP_SYS_RESOURCE

- docs/config.md
- pkg/config/config.go
- pkg/metrics/metrics.go
Just doc/text renamings...
n/a
_To run a perfscale test, comment with: `/test ebpf-node-density-heavy-25nodes`_
> NETOBSERV-2355: Rename sampling ratio/rate -> interval
